--- 
# the name file kustomization.yaml is free. other people simply use kustomize.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary
resources:
  - deployment.yaml
  - namespace.yaml